export default {
  dateFormat: 'YY/MM/DD',
  datePickerFormat: 'dd MMMM yyyy',
  filterDefaultPeriod: 30,
  filterDefaultCountriesAmount: 5,
  platformOptions: [
    { value: 'ios', label: 'IOS' },
    { value: 'android', label: 'Android' },
  ],
  aggregationOptions: [
    { value: 'days', label: 'Day' },
    { value: 'weeks', label: 'Week' },
    { value: 'months', label: 'Month' },
  ],
  countryOptions: [
    { value: 'es', label: 'Spain' },
    { value: 'pe', label: 'Peru' },
    { value: 'it', label: 'Italy' },
    { value: 'ar', label: 'Argentina' },
    { value: 'ua', label: 'Ukraine  ' },
    { value: 'fr', label: 'France' },
    { value: 'cr', label: 'Costa Rica' },
    { value: 'cl', label: 'Chile' },
    { value: 'hr', label: 'Croatia' },
    { value: 'do', label: 'Dominican Republic' },
    { value: 'ec', label: 'Ecuador' },
    { value: 'ci', label: 'Ivory Coast' },
    { value: 'ge', label: 'Georgia' },
    { value: 'gt', label: 'Guatemala' },
    { value: 'ke', label: 'Kenya' },
    { value: 'ma', label: 'Morocco' },
    { value: 'pa', label: 'Panama' },
    { value: 'pt', label: 'Portugal' },
    { value: 'pr', label: 'Puerto Rico' },
    { value: 'ro', label: 'Romania' },
    { value: 'tr', label: 'Turkey' },
    { value: 'uy', label: 'Uruguay' },
    { value: 'rs', label: 'Serbia' },
    { value: 'pl', label: 'Poland' },
    { value: 'hn', label: 'Honduras' },
    { value: 'kz', label: 'Kazakhstan' },
  ],
};
